# Generated by Django 3.2.21 on 2024-03-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('newvistor', models.IntegerField(default=0)),
                ('oldvistor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='姓名 Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='聯絡電郵 Contact Email')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='性別 gender')),
                ('title', models.CharField(max_length=30, null=True, verbose_name='標題 Title')),
                ('feedback', models.CharField(blank=True, max_length=200, null=True, verbose_name='留言 Feedback')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP Address')),
                ('location', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('visitday', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitTotalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
    ]
