# Generated by Django 3.2.21 on 2023-11-22 14:59

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_address_brand_category_deliverygroup_littlelooppicker_order_ordereditem_orderhistoryentry_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='littlelooppicker',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.brand', verbose_name='brand'),
        ),
        migrations.AddField(
            model_name='littlelooppicker',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='littlelooppicker',
            name='product_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.productclass', verbose_name='product class'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderbillingaddress', to='pages.address', verbose_name='billing_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordershippingaddress', to='pages.address', verbose_name='shipping_address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.voucher', verbose_name='voucher'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.stock', verbose_name='stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistoryentry',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistoryentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemscomment',
            name='order_items',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.ordereditem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.order', verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordernote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productclass',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.sale', verbose_name='sale'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.stocklocation', verbose_name='location'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('available_on', models.DateField()),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True, verbose_name='狀態')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.brand', verbose_name='brand')),
                ('category', models.ManyToManyField(to='pages.Category', verbose_name='category')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.productclass', verbose_name='product class')),
                ('sale', models.ManyToManyField(blank=True, to='pages.Sale', verbose_name='sale')),
            ],
        ),
        migrations.AddField(
            model_name='littlelooppicker',
            name='product',
            field=models.ManyToManyField(blank=True, to='pages.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.product', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.product', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.product', verbose_name='product'),
        ),
    ]
