# Generated by Django 3.2.21 on 2023-11-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20231122_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '處理中'), (2, '已發貨'), (0, '已完成')], verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=True, null=True),
        ),
    ]
