# Generated by Django 3.2.21 on 2024-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='is_show'),
        ),
    ]
