# Generated by Django 3.2.21 on 2023-11-25 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20231124_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='stock',
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderbillingaddress', to='pages.address', verbose_name='billing_address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cartcomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordershippingaddress', to='pages.address', verbose_name='shipping_address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '處理中'), (2, '已發貨'), (0, '已完成')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
    ]
