# Generated by Django 3.2.21 on 2023-11-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20231125_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last_status_change'),
        ),
        migrations.AlterField(
            model_name='orderitemscomment',
            name='comment_day',
            field=models.DateTimeField(),
        ),
    ]
