# Generated by Django 3.2.21 on 2023-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20231126_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='product_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='product_name'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='unit_price_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='unit_price_gross'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='unit_price_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='unit_price_net'),
        ),
    ]
