# Generated by Django 3.2.21 on 2023-11-26 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20231126_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
