# Generated by Django 3.2.21 on 2023-11-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_order_paid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(),
        ),
    ]
