# Generated by Django 3.2.21 on 2023-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_order_paid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='tatol'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='stock_location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='stock_location'),
        ),
    ]
