# Generated by Django 3.2.21 on 2023-11-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20231126_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaulticon.jpeg', null=True, upload_to='avatars/'),
        ),
    ]
