# Generated by Django 3.2.21 on 2023-12-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20231202_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_address_1',
            field=models.CharField(max_length=50, verbose_name='區域/地區/街道名稱及號碼'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used',
            field=models.PositiveIntegerField(default=0, verbose_name='used'),
        ),
    ]
