# Generated by Django 3.2.21 on 2023-12-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20231203_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名 Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡電郵 Contact Email')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='性別 gender')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='標題 Title')),
                ('feedback', models.CharField(blank=True, max_length=200, null=True, verbose_name='留言 Feedback')),
            ],
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='limit',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used',
            field=models.IntegerField(default=0, verbose_name='used'),
        ),
    ]
