# Generated by Django 3.2.21 on 2023-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20231204_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='聯絡電郵 Contact Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='姓名 Name'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='標題 Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, '處理中'), (2, '已發貨'), (3, '已完成')], default=1, verbose_name='status'),
        ),
    ]
