# Generated by Django 3.2.21 on 2023-12-04 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20231204_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='littlelooppicker',
            name='priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', '請輸入數字')]),
        ),
    ]
