# Generated by Django 3.2.21 on 2023-12-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20231205_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemscomment',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.ordereditem'),
        ),
    ]
