# Generated by Django 3.2.21 on 2024-03-20 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_status_change', models.DateTimeField(auto_now=True, null=True, verbose_name='last_status_change')),
                ('status', models.IntegerField(choices=[(1, '處理中'), (2, '已發貨'), (3, '已完成')], default=1, verbose_name='status')),
                ('total', models.CharField(blank=True, default='0', max_length=500, null=True, verbose_name='tatol')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='discount_amount')),
                ('discount_name', models.CharField(blank=True, max_length=50, verbose_name='discount_name')),
                ('transaction_id', models.CharField(blank=True, max_length=50, verbose_name='transaction_id')),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('cartcomplete', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderbillingaddress', to='accounts.address', verbose_name='billing_address')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ordershippingaddress', to='accounts.address', verbose_name='shipping_address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='product_name')),
                ('stock_location', models.CharField(blank=True, max_length=50, null=True, verbose_name='stock_location')),
                ('unit_price_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='unit_price_gross')),
                ('unit_price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='unit_price_net')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_to', models.CharField(max_length=50, verbose_name='apply to')),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount_value')),
                ('discount_value_type', models.CharField(max_length=50, verbose_name='discount_value_type')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('usage_limit', models.IntegerField(verbose_name='usage limit')),
                ('used', models.IntegerField(default=0, verbose_name='used')),
            ],
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='content')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('comment_day', models.DateTimeField(auto_now=True)),
                ('order_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.ordereditem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, verbose_name='comment')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.voucher', verbose_name='voucher'),
        ),
        migrations.CreateModel(
            name='DeliveryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(verbose_name='last_updated')),
                ('shipping_method_name', models.CharField(max_length=50, verbose_name='shipping_method_name')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='shipping_price')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='tracking_number')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order', verbose_name='order')),
            ],
        ),
    ]
