# Generated by Django 3.2.21 on 2024-03-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='description')),
                ('hidden', models.BooleanField(verbose_name='hidden')),
                ('level', models.PositiveIntegerField(verbose_name='level')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_on', models.DateField()),
                ('desc', models.TextField()),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True, verbose_name='狀態')),
                ('sale_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.brand', verbose_name='brand')),
                ('category', models.ManyToManyField(to='products.Category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_variant', models.BooleanField(verbose_name='has variant')),
                ('is_shipping_required', models.BooleanField(verbose_name='is shipping required')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('type', models.CharField(max_length=50, verbose_name='type')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='cost price')),
                ('quanity', models.IntegerField(verbose_name='quanity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.stocklocation', verbose_name='location')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('priority', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.category', verbose_name='category')),
                ('product', models.ManyToManyField(blank=True, to='products.Product', verbose_name='product')),
                ('product_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.productclass', verbose_name='product class')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=50, verbose_name='alt')),
                ('image', models.ImageField(upload_to='product/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.product', verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='productclass',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.sale', verbose_name='sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.productclass', verbose_name='product class'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.ManyToManyField(blank=True, to='products.Sale', verbose_name='sale'),
        ),
    ]
